import { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { formatDate } from '../utils/formatters';
import LoadingSpinner from './LoadingSpinner';
import AttendanceCalendar from './AttendanceCalendar';
import { API_URL } from '../api';

export default function MyProfile() {
  const [profile, setProfile] = useState(null);
  const [loading, setLoading] = useState(true);
  const [showChangePassword, setShowChangePassword] = useState(false);
  const [passwordForm, setPasswordForm] = useState({ old_password: '', new_password: '', confirm_password: '' });
  const [passwordError, setPasswordError] = useState('');
  const [attMonth, setAttMonth] = useState(new Date());

  useEffect(() => { loadProfile(); }, []);
  const loadProfile = async () => { setLoading(true); try { const token = localStorage.getItem('token'); const employee = JSON.parse(localStorage.getItem('employee')); const res = await fetch(`${API_URL}/api/employees/${employee.id}`, { headers: { 'Authorization': `Bearer ${token}` } }); setProfile(await res.json()); } catch {} setLoading(false); };
  const handleChangePassword = async (e) => { e.preventDefault(); setPasswordError(''); if (passwordForm.new_password !== passwordForm.confirm_password) { setPasswordError('New passwords do not match'); return; } if (passwordForm.new_password.length < 6) { setPasswordError('Password must be at least 6 characters'); return; } try { const token = localStorage.getItem('token'); const res = await fetch(`${API_URL}/api/auth/change-password`, { method: 'POST', headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ old_password: passwordForm.old_password, new_password: passwordForm.new_password }) }); if (!res.ok) { const error = await res.json(); setPasswordError(error.detail || 'Failed to change password'); return; } alert('Password changed successfully! Please login again.'); localStorage.removeItem('token'); localStorage.removeItem('employee'); window.location.reload(); } catch { setPasswordError('Failed to change password'); } };

  if (loading) return <LoadingSpinner size="lg" text="Loading profile..." />;
  if (!profile) return <div className="text-center py-12 text-glass-muted">Profile not found</div>;

  return (
    <div className="max-w-4xl mx-auto">
      <div className="glass-card overflow-hidden animate-glass-in">
        <div className="p-8" style={{ background: 'linear-gradient(135deg, #eef2ff, #f5f3ff)' }}>
          <div className="flex items-center gap-6">
            <div className="w-24 h-24 rounded-full flex items-center justify-center text-3xl font-bold text-white shadow-lg" style={{ background: '#6366f1', boxShadow: '0 8px 24px rgba(99,102,241,0.30)' }}>{profile.name.charAt(0).toUpperCase()}</div>
            <div><h1 className="text-3xl font-bold text-glass-primary">{profile.name}</h1><p className="text-lg text-glass-secondary mt-1">{profile.job_role || 'Employee'}</p><p className="text-sm text-glass-muted mt-2">Employee ID: {profile.employee_id || 'N/A'}</p></div>
          </div>
        </div>
        <div className="p-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div><h3 className="text-sm font-semibold text-glass-muted uppercase mb-4">Personal Information</h3><div className="space-y-3"><div><span className="text-sm text-glass-secondary">Contact Number</span><div className="font-medium text-glass-primary">{profile.phone}</div></div><div><span className="text-sm text-glass-secondary">Email Address</span><div className="font-medium text-glass-primary">{profile.email || 'N/A'}</div></div><div><span className="text-sm text-glass-secondary">Address</span><div className="font-medium text-glass-primary">{profile.address || 'N/A'}</div></div></div></div>
            <div><h3 className="text-sm font-semibold text-glass-muted uppercase mb-4">Employment Details</h3><div className="space-y-3"><div><span className="text-sm text-glass-secondary">Date of Joining</span><div className="font-medium text-glass-primary">{profile.joining_date ? formatDate(profile.joining_date) : 'N/A'}</div></div><div><span className="text-sm text-glass-secondary">Status</span><div><span className={`glass-badge ${profile.status === 'active' ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'}`}>{profile.status === 'active' ? 'Active' : 'Non-Active'}</span></div></div>{profile.status === 'non-active' && profile.date_of_leaving && <div><span className="text-sm text-glass-secondary">Date of Leaving</span><div className="font-medium text-glass-primary">{formatDate(profile.date_of_leaving)}</div></div>}</div></div>
          </div>
          <div className="mt-8 pt-8" style={{ borderTop: '1px solid #e5e5ea' }}>
            <h3 className="text-sm font-semibold text-glass-muted uppercase mb-4">Leave Summary</h3>
            {profile.paid_leave_quota > 0 && <div className="mb-6 p-4 glass-subtle" style={{ background: '#eff6ff' }}><div className="flex justify-between items-center mb-2"><span className="text-sm font-semibold text-blue-900">Monthly Paid Leave Quota</span><span className="text-2xl font-bold text-blue-600">{profile.paid_leave_remaining || 0} / {profile.paid_leave_quota}</span></div><div className="w-full rounded-full h-2" style={{ background: 'rgba(147,197,253,0.50)' }}><div className="bg-blue-600 h-2 rounded-full transition-all" style={{ width: `${((profile.paid_leave_remaining || 0) / profile.paid_leave_quota) * 100}%` }} /></div><p className="text-xs text-blue-700 mt-2">Used: {profile.paid_leave_used || 0} | Remaining: {profile.paid_leave_remaining || 0}{profile.paid_leave_remaining === 0 && <span className="font-bold text-red-600"> - No More Paid Leaves Available This Month</span>}</p></div>}
            <h4 className="text-sm font-medium text-glass-secondary mb-3">Current Month</h4>
            <div className="flex gap-6 mb-4"><div className="flex items-center gap-2"><span className="w-4 h-4 rounded bg-red-200"></span><span className="text-sm text-glass-primary">Leave: {profile.leave_counts?.leave || 0} days</span></div><div className="flex items-center gap-2"><span className="w-4 h-4 rounded bg-yellow-200"></span><span className="text-sm text-glass-primary">Half Day: {profile.leave_counts?.half_day || 0} days</span></div><div className="flex items-center gap-2"><span className="w-4 h-4 rounded bg-blue-200"></span><span className="text-sm text-glass-primary">Paid Leave: {profile.leave_counts?.paid_leave || 0} days</span></div><div className="flex items-center gap-2"><span className="w-4 h-4 rounded bg-indigo-200"></span><span className="text-sm text-glass-primary">Work From Home: {profile.leave_counts?.wfh || 0} days</span></div></div>
            {profile.monthly_salary && <div className="mt-4 p-4 glass-subtle" style={{ background: 'linear-gradient(135deg, #f0fdf4, #dcfce7)' }}><h5 className="text-sm font-bold text-green-900 mb-3">💰 Salary Breakdown</h5><div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-glass-secondary">Base Salary:</span><span className="font-semibold text-glass-primary">₹{parseFloat(profile.monthly_salary).toLocaleString('en-IN')}</span></div><div className="flex justify-between"><span className="text-glass-secondary">Days in Month:</span><span className="font-medium text-glass-primary">{profile.days_in_month || '-'}</span></div><div className="flex justify-between"><span className="text-glass-secondary">Per Day Salary:</span><span className="font-medium text-glass-primary">₹{profile.per_day_salary ? parseFloat(profile.per_day_salary).toLocaleString('en-IN') : '-'}</span></div><div className="my-2" style={{ borderTop: '1px solid rgba(34,197,94,0.25)' }}></div><div className="flex justify-between text-red-700"><span className="font-medium">Deduction (Leave + Half Day):</span><span className="font-bold">- ₹{profile.deduction_amount ? parseFloat(profile.deduction_amount).toLocaleString('en-IN') : '0'}</span></div><div className="my-2" style={{ borderTop: '2px solid rgba(34,197,94,0.35)' }}></div><div className="flex justify-between text-lg"><span className="font-bold text-green-900">Net Salary:</span><span className="font-bold text-green-600">₹{profile.net_salary ? parseFloat(profile.net_salary).toLocaleString('en-IN') : '-'}</span></div></div><p className="text-xs text-glass-muted mt-3 pt-3" style={{ borderTop: '1px solid rgba(34,197,94,0.20)' }}>📋 Leave = Full day deducted | Half Day = 0.5 day deducted | Paid Leave = No deduction</p></div>}
          </div>
          <div className="mt-8 pt-8" style={{ borderTop: '1px solid #e5e5ea' }}><h3 className="text-sm font-semibold text-glass-muted uppercase mb-4">My Attendance</h3><AttendanceCalendar employeeId={profile.id} employeeName={profile.name} month={attMonth} setMonth={setAttMonth} leaveDays={profile.leave_days} leaveCounts={profile.leave_counts} paidLeaveQuota={profile.paid_leave_quota || 0} paidLeaveRemaining={profile.paid_leave_remaining || 0} readOnly /></div>
          <div className="mt-6"><button onClick={() => setShowChangePassword(true)} className="glass-btn w-full px-4 py-2">🔒 Change Password</button></div>
        </div>
      </div>
      {showChangePassword && createPortal(<div className="fixed inset-0 glass-overlay flex items-center justify-center p-4 z-50 overflow-y-auto"><div className="glass-strong max-w-md w-full p-6 my-8 max-h-[90vh] overflow-y-auto animate-glass-in"><h2 className="text-xl font-bold mb-4 text-glass-primary">Change Password</h2>{passwordError && <div className="mb-4 p-3 rounded-lg text-sm" style={{ background: '#fef2f2', border: '1px solid #fca5a5', color: '#991b1b' }}>{passwordError}</div>}<form onSubmit={handleChangePassword} className="space-y-4"><div><label className="block text-sm font-medium text-glass-secondary mb-1">Current Password</label><input type="password" value={passwordForm.old_password} onChange={(e) => setPasswordForm({...passwordForm, old_password: e.target.value})} className="glass-input w-full px-3 py-2" required autoComplete="current-password" /></div><div><label className="block text-sm font-medium text-glass-secondary mb-1">New Password</label><input type="password" value={passwordForm.new_password} onChange={(e) => setPasswordForm({...passwordForm, new_password: e.target.value})} className="glass-input w-full px-3 py-2" required minLength={6} autoComplete="new-password" /><p className="text-xs text-glass-muted mt-1">Minimum 6 characters</p></div><div><label className="block text-sm font-medium text-glass-secondary mb-1">Confirm New Password</label><input type="password" value={passwordForm.confirm_password} onChange={(e) => setPasswordForm({...passwordForm, confirm_password: e.target.value})} className="glass-input w-full px-3 py-2" required minLength={6} autoComplete="new-password" /></div><div className="flex gap-3 pt-4"><button type="submit" className="glass-btn flex-1 px-4 py-2">Change Password</button><button type="button" onClick={() => { setShowChangePassword(false); setPasswordForm({ old_password: '', new_password: '', confirm_password: '' }); setPasswordError(''); }} className="px-4 py-2 rounded-lg font-medium" style={{ background: '#f3f4f6', color: '#424245' }}>Cancel</button></div></form></div></div>, document.body)}
    </div>
  );
}
